# Refer to the var.tf file for description of the variables for this deployment
deployment_prefix = ""
aws_vpc = ""
aws_subnet_az1 = ""
aws_subnet_az2 = ""
aws_subnet_az3 = ""
xsoar_main_instance_type = ""
xsoar_host_instance_type = ""
xsoar_ami = ""
opensearch_instance_type = ""
xsoar_main_opensearch_domain = ""
opensearch_master_user = ""
opensearch_master_password = ""
xsoar_download_url = ""
